### ISSUE TITLE
[QUESTION] what does the push button? 

### ISSUE THREAD

**Issue by Knarf2807** [howie-j/OpenSolder#6]
For me the push button in the encoder has nö funktion. Is that right or is it a bug in my soldering work?

I can't find a fault with my Multimeter and your KiCad files. 

And if it is right: Why is 400°C the highest target temperatur?

Thanks a lot for your answer and your work.

Frank

**Comment by howie-j** [comment]
Hi, thanks a lot for testing and feedback!

The push button has no function as of now, however i plan to implement a simple menu for changing default values (default temp, standby temp etc), and then the push button will trigger that menu.

During development i used the push button as an on/off switch, so that i would not burn up my tips if i had any bugs in my code😅 So far no acccidents! That function was removed before i published the code.

There is no reason for the 400'C max temp, other than that i never solder above 350-380'C. You can change most parameters such as temps, delays etc in this file before compiling: [opensolder.h](https://github.com/howie-j/OpenSolder/blob/main/firmware/opensolder/Core/Inc/opensolder.h#L25)

I would recommend not setting the temp above 400-450'C, as that will shorten the tip life drastically. Also because of the quick temp drop reaction and abundant heating power, i find i can lower the temp probably 20-30'C below other stations i have used in the past.

Håvard

**Comment by Knarf2807** [comment]
Thank you very much for your fast answer. :-)

Than I be glad, that it is no solder-fault from me. At the beginning I expected a menu like you describe above. 
The truth: I stressed the ENC-Footprint on the PCB "a little bit" because I desoldered it. The ENC No. 1 is allready not alive. I rebuild the front and the bag for me and hope I will finish today. 

I come from a Ersa Pico and there I need sometimes the 450°C for desoldering or big planes, also with a 1,6mm chissel. But what I realized with the JBC T245: I need much less heat than with the Ersa Pico. That's why I believe 400°C would be enough for me. The cardridge-system is much better than the Ersa-heater.

Frank
